### ISSUE TITLE
Queue high size

### ISSUE THREAD

**Issue by thalysmarciobn** [codedcosmos/CometBot#4]
[01:00:59] [JDA MainWS-ReadThread] : net.dv8tion.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
        at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
        at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:260)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:235)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:201)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:211)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:471)
        at codedcosmos.hyperdiscord.chat.messages.BookMessage.clearReactions(BookMessage.java:101)
        at codedcosmos.cometbot.guild.context.DynamicMessages.sendQueueMessage(DynamicMessages.java:109)
        at codedcosmos.cometbot.guild.commands.Queue.run(Queue.java:42)
        at codedcosmos.hyperdiscord.command.CommandListener.processMessageRecievedEvent(CommandListener.java:74)
        at codedcosmos.hyperdiscord.command.CommandListener.onMessageReceived(CommandListener.java:47)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:428)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:921)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:808)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:786)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:959)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)[01:00:59] [JDA MainWS-ReadThread] : net.dv8tion.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
        at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
        at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:260)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:235)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:201)
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:211)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:471)
        at codedcosmos.hyperdiscord.chat.messages.BookMessage.clearReactions(BookMessage.java:101)
        at codedcosmos.cometbot.guild.context.DynamicMessages.sendQueueMessage(DynamicMessages.java:109)
        at codedcosmos.cometbot.guild.commands.Queue.run(Queue.java:42)
        at codedcosmos.hyperdiscord.command.CommandListener.processMessageRecievedEvent(CommandListener.java:74)
        at codedcosmos.hyperdiscord.command.CommandListener.onMessageReceived(CommandListener.java:47)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:428)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:921)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:808)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:786)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:959)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by codedcosmos** [comment]
What where you doing before these error messages appeared. What commands triggered it?

**Comment by thalysmarciobn** [comment]
When I a queue a playlist with 100 songs, he can't show all queue list or I think is better do a list with pagination

**Comment by codedcosmos** [comment]
What is the output of `.version`?

I have run the following commands which loads a 600 song playlist and I'm not encountering any issues. Even when using the pages created by the `.queue` command.

```
.play https://www.youtube.com/watch?v=rGsEb1xTRGg&list=PLe8jmEHFkvsaDOOWcREvkgFoj6MD0pQ67
.queue
```

**Comment by codedcosmos** [comment]
I'm going to close this for now as it is likely fixed by now. If the error comes back feel free to make another issue post.

**Comment by codedcosmos** [comment]
Also make sure the bot has permission to manage roles.
